import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/providers/convex-client-provider";
const inter = Inter({ subsets: ["latin"] });

import { Analytics } from "@vercel/analytics/react"
export const metadata: Metadata = {
  title: "Travel Tracer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <Analytics />
      <ConvexClientProvider>{children}</ConvexClientProvider>

      </body>
    </html>
  );
}
